spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        preferIpAddress: true
  application:
    name: terraform-demo-app
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    servlet:
      path: /
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: always
    # ============================== druid ============================== #
    druid:
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat, wall, log4j

  # ============================= spring jpa  ============================= #
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hbm2ddl.auto: update
        jdbc.lob.non_contextual_creation: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
server:
  port: 9999
